[package]
name = "charmap-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.19.0"
eframe = { version = "0.19.0", features = ["persistence"] }
copypasta-ext = "0.3.9"
once_cell = "1.16.0"
